import React, { Children } from "react"
import Search from "./Search"


export const metadata = {
  title: 'Search Page',
  description: 'Generated by Imtiaj',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="flex space-x-4 divide-x-2 p-5">
      <div>
        <h1>Search Page h1</h1>
      </div>

      <div className="flex-1 pl-5">
        <Search />
        <div>{children}</div>
      </div>
    </main>
  )
}
